name: 02-Execute a JMeter Test Plan and Archive Results

on:
#  push:
#    branches:
#      - main  # Run tests on pushes to the main branch
  workflow_dispatch: # Allow manual trigger of this workflow

jobs:
  run-jmeter-tests:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Install JMeter
      - name: Install JMeter
        run: |
          sudo apt-get update
          sudo apt-get install -y default-jdk wget
          wget https://downloads.apache.org/jmeter/binaries/apache-jmeter-5.6.3.tgz
          tar -xvzf apache-jmeter-5.6.3.tgz
          mv apache-jmeter-5.6.3 ~/jmeter
#          sudo apt-get install -y jmeter # This can be used to install JMeter directly avoiding extractions

      # Step 3: Validate if JMeter test plan exists
      - name: Validate JMeter test plan exists
        run: |
          if [ ! -f test-plan/test-plan-jmeter-website.jmx ]; then
            echo "Error: JMeter test plan not found!"
            exit 1
          fi

      # Step 4: Run JMeter test plan
      - name: Run JMeter test plan
        run: |
          mkdir -p results test-results
#         ~/jmeter/bin/jmeter -n -t test-plan/test-plan-jmeter-website.jmx -l results/results.csv -j results/jmeter.log
#          ~/jmeter/bin/jmeter -n -t test-plan/test-plan-jmeter-website.jmx -l results/results.csv -j results/jmeter.log || (echo "JMeter execution failed!" && cat results/jmeter.log && exit 1)
          ~/jmeter/bin/jmeter \
          -n \
          -t test-plan/test-plan-jmeter-website.jmx \
          -l results/results.csv \
          -j results/jmeter.log || ( \
              echo "JMeter execution failed!" && \
              cat results/jmeter.log && \
          exit 1 \
          )

      #Step 5: Save results as artifacts
      - name: Upload results folder as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-results
          path: results/