#Events that trigger workflows
name : 07-Run the steps based on the event schedule

on:
  schedule:
    - cron: '*/10 * * * 1,3'
    - cron: '*/5 * * * 2,4'

  workflow_dispatch: # Allow manual trigger of this workflow
    
jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Not on Monday or Wednesday
        if: github.event.schedule != '30 5 * * 1,3'
        run: echo "This step will be skipped on Monday and Wednesday"
      - name: Run every time
        run: echo "This step will always run"

