name: 03-Run JMeter Tests with HTML Reports

on:
  workflow_dispatch: # Allow manual trigger of this workflow

jobs:
  run-jmeter-tests:
    runs-on: ubuntu-latest

    env:
      JMETER_VERSION: "5.6.3"
      JMETER_HOME: "${HOME}/jmeter"
      TEST_PLAN_PATH: "test-plan/test-plan-jmeter-website.jmx"
      TEST_REPORT_FOLDER: "results"


    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Install JDK and required tools
      - name: Install JDK and wget
        run: |
          sudo apt-get update
          sudo apt-get install -y default-jdk wget

      # Step 3: Cache JMeter installation
      - name: Cache JMeter
        uses: actions/cache@v2
        with:
          path: ~/.cache/jmeter
          key: jmeter-${{ env.JMETER_VERSION }}
          restore-keys: |
            jmeter-${{ env.JMETER_VERSION }}-

      # Step 4: Install JMeter (if not cached)
      - name: Install JMeter
        run: |
          if [ ! -d "$HOME/jmeter" ]; then
            wget https://downloads.apache.org/jmeter/binaries/apache-jmeter-${JMETER_VERSION}.tgz
            tar -xvzf apache-jmeter-${JMETER_VERSION}.tgz
            mv apache-jmeter-${JMETER_VERSION} ~/jmeter
          else
            echo "Using cached JMeter version."
          fi


      # Step 5: Check if JMX exists in the given path
      - name: Validate JMeter test plan
        run: |
          if [ ! -f "${{ env.TEST_PLAN_PATH }}" ]; then
            echo "Error: JMeter test plan not found at ${{ env.TEST_PLAN_PATH }}!"
            exit 1
          fi


      # Step 6: Run JMeter test plan and generate HTML reports
      - name: Run JMeter test plan and generate HTML reports
        run: |
          mkdir -p ${{ env.TEST_REPORT_FOLDER }}
          $HOME/jmeter/bin/jmeter \
          -n \
          -t ${{ env.TEST_PLAN_PATH }} \
          -l ${{ env.TEST_REPORT_FOLDER }}/results.csv \
          -j ${{ env.TEST_REPORT_FOLDER }}/jmeter.log \
          -e -f \
          -o ${{ env.TEST_REPORT_FOLDER }}/reports || ( \
          echo "JMeter execution failed! Check logs." && \
          cat ${{ env.TEST_REPORT_FOLDER }}/jmeter.log && \
          exit 1 \
          )

      # Step 7: Move XML test result file to results folder (if exists)
      - name: Move test-result.xml if available
        run: |
          if [ -f "$GITHUB_WORKSPACE/test-result.xml" ]; then
            mv "$GITHUB_WORKSPACE/test-result.xml" ${{ env.TEST_REPORT_FOLDER }}/test-result.xml
            echo "test-result.xml moved successfully."
          else
            echo "Warning: test-result.xml not found!"
          fi

      # Step 8: Save results as artifacts
      - name: Upload results folder as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-results
          path: ${{ env.TEST_REPORT_FOLDER }}